author: Rajarshi Tiwari
email: rajarshi84@gmail.com
title: Python Codes
url: 'https://rajarshitiwari.github.io'
baseurl: '/python-codes'

# theme: jekyll-theme-primer

markdown_ext: md
toc:
  enabled: true
  h_min: 1
  h_max: 3

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-toc

remote-theme: pages-themes/primer@0.2.0

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful